Project-Development-Phase/sprint4/routes.py
from flask import Blueprint, render_template, request, jsonify, session, redirect, url_for
from sprint3.utils import *
from sprint4.utils import donor_req_count, donate_req, donors_info
import datetime

sprint4 = Blueprint('sprint4', __name__, template_folder='templates', static_folder='static', static_url_path='/sprint4/static')


@sprint4.route('/donate-plasma', methods=['POST', 'GET'])
def donate():
    if 'user' in session:
        if request.method == 'POST':
            response = dict()
            select = request.json
            if 'state' in select and 'city' in select and 'locality' in select:
                if select['state'] != 'all' and select['city'] == 'all' and select['locality'] == 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and STATE=? order by NAME'
                    response['filter'] = filter_by_one_param(sql, select['state'])
                    temp = filter_by_one(select['state'], None, None)
                    response['filterCity'] = temp['res1']
                    response['filterLocality'] = temp['res2']
                    response['filter_city_select'] = 'YES'
                    response['filter_locality_select'] = 'YES'
                    return jsonify(response)

                elif select['state'] != 'all' and select['city'] != 'all' and select['locality'] == 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and STATE=? and CITY=? order by NAME'
                    response['filter'] = filter_by_two_params(sql, select['state'], select['city'])
                    response['filter_locality_select'] = 'YES'
                    response['filterLocality'] = filter_by_two(select['state'], select['city'], None)
                    return jsonify(response)

                elif select['state'] != 'all' and select['city'] == 'all' and select['locality'] != 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and STATE=? and LOCALITY=? order by NAME'
                    response['filter'] = filter_by_two_params(sql, select['state'], select['locality'])
                    response['filter_city_select'] = 'YES'
                    response['filterLocality'] = filter_by_two(select['state'], None, select['locality'])
                    return jsonify(response)

                elif select['state'] == 'all' and select['city'] != 'all' and select['locality'] == 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and CITY=? order by NAME'
                    response['filter'] = filter_by_one_param(sql, select['city'])
                    temp = filter_by_one(None, select['city'], None)
                    response['filter_locality_select'] = 'YES'
                    response['filter_state_select'] = 'YES'
                    response['filterState'] = temp['res1']
                    response['filterLocality'] = temp['res2']
                    return jsonify(response)

                elif select['state'] == 'all' and select['city'] != 'all' and select['locality'] != 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and CITY=? and LOCALITY=? order by NAME'
                    response['filter'] = filter_by_two_params(sql, select['city'], select['locality'])
                    response['filter_state_select'] = 'YES'
                    response['filterState'] = filter_by_two(None, select['city'], select['locality'])
                    return jsonify(response)

                elif select['state'] == 'all' and select['city'] == 'all' and select['locality'] != 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and LOCALITY=? order by NAME'
                    response['filter'] = filter_by_one_param(sql, select['locality'])
                    temp = filter_by_one(None, None, select['locality'])
                    response['filter_state_select'] = 'YES'
                    response['filter_city_select'] = 'YES'
                    response['filterState'] = temp['res1']
                    response['filterCity'] = temp['res2']
                    return jsonify(response)

                elif select['state'] == 'all' and select['city'] == 'all' and select['locality'] == 'all':
                    sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' order by NAME'
                    response['filter'] = display_donors(sql)
                    response['filter_state_select'] = 'YES'
                    response['filter_city_select'] = 'YES'
                    response['filter_locality_select'] = 'YES'
                    temp = display_all_option(sql)
                    response['filterState'] = temp['res1']
                    response['filterCity'] = temp['res2']
                    response['filterCity'] = temp['res3']
                    return jsonify(response)

                sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' and STATE=? and CITY=? and LOCALITY=? order by NAME'
                stmt = ibm_db.prepare(conn, sql)
                ibm_db.bind_param(stmt, 1, select['state'])
                ibm_db.bind_param(stmt, 2, select['city'])
                ibm_db.bind_param(stmt, 3, select['locality'])
                ibm_db.execute(stmt)
                fetch = ibm_db.fetch_assoc(stmt)

                res = []
                while fetch:
                    res.append(fetch)
                    fetch = ibm_db.fetch_assoc(stmt)
                response['filter'] = res
                return jsonify(response)
            elif 'email' in select:
                counter = donor_req_count(session['donor-email'])

                date_format = "%Y-%m-%d %H:%M:%S"
                if counter['1'] < 5:
                    temp = donors_info(session['donor-email'])
                    if counter['1'] == 0:
                        donate_req(session['donor-email'], select['email'], select['name'], temp['B_group'], temp['Name'], temp['Contact'])
                        response['donate_req_status'] = 'Success'
                    else:
                        sql = 'select ORG_EMAIL from DONATE_REQUESTS where DONOR_EMAIL=? and ORG_EMAIL=?'
                        stmt = ibm_db.prepare(conn, sql)
                        ibm_db.bind_param(stmt, 1, session['donor-email'])
                        ibm_db.bind_param(stmt, 2, select['email'])
                        ibm_db.execute(stmt)
                        fetch = ibm_db.fetch_assoc(stmt)

                        if fetch:
                            response['donate_req_status'] = 'Already'
                        else:
                            donate_req(session['donor-email'], select['email'], select['name'], temp['B_group'], temp['Name'], temp['Contact'])
                            response['donate_req_status'] = 'Success'
                elif counter['1'] >= 5:
                    sql = 'select * from DONATE_REQUESTS where DONOR_EMAIL=?'
                    stmt = ibm_db.prepare(conn, sql)
                    ibm_db.bind_param(stmt, 1, session['donor-email'])
                    ibm_db.execute(stmt)
                    fetch = ibm_db.fetch_assoc(stmt)

                    while fetch:
                        no_of_days = (datetime.datetime.now() - datetime.datetime.strptime(fetch['REQUEST_MADE_TIME'], date_format)).days
                        if fetch['ORG_EMAIL'] == 'email' and no_of_days >= 2:
                            sql2 = 'delete from DONATE_REQUESTS where DONOR_EMAIL=? and ORG_EMAIL=?'
                            stmt2 = ibm_db.prepare(conn, sql2)
                            ibm_db.bind_param(stmt2, 1, session['donor-email'])
                            ibm_db.bind_param(stmt2, 2, fetch['ORG_EMAIL'])
                            ibm_db.execcute(stmt2)
                        fetch = ibm_db.fetch_assoc(stmt)

                    if donor_req_count(session['donor-email'])['1'] < 5:
                        temp = donors_info(session['donor-email'])
                        donate_req(session['donor-email'], select['email'], select['name'], temp['B_group'], temp['Name'], temp['Contact'])
                        response['donate_req_status'] = 'Success'
                    else:
                        response['donate_req_status'] = 'After'
                return response
        else:
            sql = 'select * from ORGANISATION_DETAILS where APPROVED=\'YES\' order by NAME'
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.execute(stmt)
            fetch = ibm_db.fetch_assoc(stmt)

            res, cities, states, locality = [], [], [], []
            while fetch:
                if fetch['CITY'] not in cities:
                    cities.append(fetch['CITY'])
                if fetch['STATE'] not in states:
                    states.append(fetch['STATE'])
                if fetch['LOCALITY'] not in locality:
                    locality.append(fetch['LOCALITY'])
                res.append(fetch)
                fetch = ibm_db.fetch_assoc(stmt)

            states.sort()
            cities.sort()
            locality.sort()
            return render_template('donate.html', res=res, cities=cities, states=states, locality=locality)
    else:
        return redirect(url_for('sprint3.login_as', redirect_to='donor'))


@sprint4.route('/donor-profile', methods=['GET', 'POST'])
def donor_profile():
    if 'user' in session:
        if request.method == 'POST':
            response = dict()
            org_email = request.json
            sql = 'delete from DONATE_REQUESTS where DONOR_EMAIL=? and ORG_EMAIL=?'
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, session['donor-email'])
            ibm_db.bind_param(stmt, 2, org_email['org-email'])
            ibm_db.execute(stmt)

            response['CancelStatus'] = 'True'
            return response
        else:

Project-Development-Phase/sprint4/templates/donate.html
{% extends 'index.html' %}
{% block title %}Donate Plasma{% endblock title %}


{% block content %}
    <div class="fullscreen">
        <nav class="navbar bg-white">
            <div class="ps-3">
                <a class="navbar-icon" href="{{ url_for('sprint1.home') }}">Plasma Donor</a>
                <div class="nav-content">
                    <a class="nav-content-item" href="{{ url_for('sprint1.home') }}">HOME</a>
                </div>
            </div>
            <div class="nav-content-right">
                <a class="nav-content-item" href="{{ url_for('sprint4.donor_profile') }}">PROFILE</a>
                <a class="nav-content-item" href="/logout">LOGOUT</a>
            </div>
        </nav>
        <div class="container p-5" style="height: 91vh; overflow: scroll">
            <div class="row row-cols-3 mb-4">
                <div class="col">
                    <label for="DonorStateFilter" class="form-label">State</label>
                    <select class="form-select DonoteFilter" id="DonorStateFilter">
                        <option selected value="all">All</option>
                        {% for state in states %}
                            <option value="{{ state }}">{{ state }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col">
                    <label for="DonorCityFilter" class="form-label">City</label>
                    <select class="form-select DonoteFilter" id="DonorCityFilter">
                        <option selected value="all">All</option>
                        {% for city in cities %}
                            <option value="{{ city }}">{{ city }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col">
                    <label for="DonorLocalityFilter" class="form-label">Locality</label>
                    <select class="form-select DonoteFilter" id="DonorLocalityFilter">
                        <option selected value="all">All</option>
                        {% for local in locality %}
                            <option value="{{ local }}">{{ local }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="container w-50 mb-3">
                <div class="row row-cols-2">
                    <div class="col-2 pe-0" style="margin: auto 0; text-align: right">
                        <label for="OrgSearch">Search:</label>
                    </div>
                    <div class="col-10">
                        <input type="search" class="form-control" id="OrgSearch" placeholder="Search">
                    </div>
                </div>
            </div>
            <table class="table" style="text-align: center;border: 1px solid lightgrey">
                <thead class="table-secondary">
                    <tr>
                        <th scope="col">S.No</th>
                        <th scope="col">Organisation Name</th>
                        <th scope="col">Locality</th>
                        <th scope="col">City</th>
                        <th scope="col">State</th>
                        <th scope="col">Pincode</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody id="TableData">
                    {% for row in res %}
                        <tr>
                            <td style="margin: auto 0">{{ res.index(row) + 1 }}</td>
                            <td>{{ row['NAME'] }}</td>
                            <td>{{ row['LOCALITY'] }}</td>
                            <td>{{ row['CITY'] }}</td>
                            <td>{{ row['STATE'] }}</td>
                            <td>{{ row['PINCODE'] }}</td>
                            <td>
                                <button class="btn btn-primary btn-sm" id="DonateButton" data-name="{{ row['NAME'] }}" data-email="{{ row['EMAIL'] }}">Donate</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container-fluid" id="bg-spin" style="position: absolute; top: 0; bottom: 0; background-color: rgba(0,0,0,0.4); display: none; justify-content: center; align-items: center">
            <span class="spinner-border text-light" style="width: 2.5rem; height: 2.5rem;   --bs-spinner-border-width: 0.35rem;"></span>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{{ url_for('sprint4.static', filename="js/donate.js") }}"></script>
    <script>
        const csrf_token = "{{ csrf_token() }}";
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });
    </script>
{% endblock javascript %}

Project-Development-Phase/sprint4/templates/donor_profile.html
{% extends 'index.html' %}
{% block title %}Admin{% endblock title %}

{% block style %}

{% endblock style %}

{% block content %}
    <div class="fullscreen">
        <nav class="navbar bg-white">
            <div class="ps-3">
                <a class="navbar-icon" href="{{ url_for('sprint1.home') }}">Plasma Donor</a>
                <div class="nav-content">
                    <a class="nav-content-item" href="{{ url_for('sprint1.home') }}">HOME</a>
                    <a class="nav-content-item" href="{{ url_for('sprint4.donate') }}">DONATE</a>
                </div>
            </div>
            <div class="nav-content-right">
                <a class="nav-content-item" href="/logout">LOGOUT</a>

                <div class="dropstart dropdown-align">
                    <a class="fa-solid fa-bars" data-bs-toggle="dropdown" id="NavItems"></a>
                    <div class="dropdown-menu" aria-labelledby="NavItems">
                        <a class="dropdown-item" href="{{ url_for('sprint1.home') }}">HOME</a>
                        <a class="dropdown-item" href="{{ url_for('sprint4.donate') }}">DONATE</a>
                        <hr class="mb-2 mt-2">
                        <a class="dropdown-item" href="/logout">LOGOUT</a>
                    </div>
                </div>
            </div>
        </nav>

        <div class="container mt-4 mb-4" style="height: 84vh; box-shadow: 0 3px 8px rgba(0, 0, 0, 30%)">
            <div class="container w-25" style="height: 84vh; float: left; border-right: 1px solid darkgray">
                <div class="d-grid gap-1 mt-5" style="text-align: center">
                    <span class="fa-solid fa-circle-user" style="color: rgba(0,0,0,0.3); border-radius: 50%; font-size: 200px"></span>
                    <strong style="font-size: 2rem">{{ session['user'] }}</strong>
                    <span>mailaddress@gmail.com</span>
                    <span>+91 XXX-XXX-XXXX</span>
                </div>
            </div>
            <div class="container w-75" style="height: 84vh; float: left; padding: 40px 30px 20px">
                <div class="container mb-2" style="height: 37vh; overflow: scroll">
                    <table class="table" style="text-align: center;border: 1px solid lightgrey" id="AdminTable1">
                        <thead class="table-secondary">
                            <tr>
                                <th scope="col">S.No</th>
                                <th scope="col">Organisation Name</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody id="StatusTable">
                            {% for row in res %}
                                <tr>
                                    <td>{{ res.index(row) + 1 }}</td>
                                    <td>{{ row['ORG_NAME'] }}</td>
                                    <td>{{ row['REQUEST_STATUS'] }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="container" style="height: 36vh; overflow: scroll">
                    <table class="table table-sm" style="text-align: center;border: 1px solid lightgrey">
                        <thead class="table-secondary">
                            <tr>
                                <th scope="col">S.No</th>
                                <th scope="col">Organisation Name</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody id="CancelReq">
                            {% for row in res %}
                                {% if row['REQUEST_STATUS'] == 'PENDING' %}
                                    <tr>
                                        <td>{{ res.index(row) + 1 }}</td>
                                        <td>{{ row['ORG_NAME'] }}</td>
                                        <td>
                                            <button class="btn btn-sm btn-light" id="CancelButton" data-org-email="{{ row['ORG_EMAIL'] }}" style="box-shadow: 0 0 2px rgba(0,0,0,40%)">Cancel</button>
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="container-fluid" id="bg-spin" style="position: absolute; top: 0; bottom: 0; background-color: rgba(0,0,0,0.4); display: none; justify-content: center; align-items: center">
            <span class="spinner-border text-light" style="width: 2.5rem; height: 2.5rem;   --bs-spinner-border-width: 0.35rem;"></span>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script>
        const csrf_token = "{{ csrf_token() }}";
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });
    </script>
    <script src="{{ url_for('sprint4.static', filename="js/donate.js") }}"></script>
{% endblock javascript %}