Project-Development-Phase/sprint3/routes.py
from flask import Blueprint, render_template, session, request, jsonify, redirect, url_for
from main import csrf, mail
from flask_mail import Message
from sprint3.utils import *

sprint3 = Blueprint('sprint3', __name__, template_folder='templates', static_folder='static', static_url_path='/sprint3/static')


@csrf.exempt
@sprint3.route('/donor-request', methods=['GET', 'POST'])
def donor_request():
    if 'Organisation' in session:
        if request.method == 'POST':    # Filtering Table
            response = dict()
            opt = request.json
            if 'state' in opt and 'city' in opt and 'blood_group' in opt:  # filter by both CITY and STATE
                b_group = ""

                if opt['blood_group'] != 'all':
                    for i in range(len(opt['blood_group'])):
                        if i == 0:
                            b_group += "\'" + opt['blood_group'][i] + "\'"
                        else:
                            b_group += " OR BLOODGROUP=\'" + opt['blood_group'][i] + "\'"

                if opt['state'] != 'all' and opt['city'] == 'all' and opt['blood_group'] == 'all':
                    sql = 'select * from PERSONALDETAILS where STATE=?'
                    response['filters'] = filter_by_one_param(sql, opt['state'])
                    response['filter_by'] = 'State'
                    response['filter1_city'] = city_filter(opt['state'])
                    return jsonify(response)

                elif opt['state'] != 'all' and opt['city'] == 'all' and opt['blood_group'] != 'all':
                    sql = 'select * from PERSONALDETAILS where STATE=? and BLOODGROUP=' + b_group
                    response['filters'] = filter_by_one_param(sql, opt['state'])
                    return jsonify(response)

                elif opt['state'] != 'all' and opt['city'] != 'all' and opt['blood_group'] == 'all':
                    sql = 'select * from PERSONALDETAILS where STATE=? and CITY=?'
                    response['filters'] = filter_by_two_params(sql, opt['state'], opt['city'])
                    return jsonify(response)

                elif opt['state'] == 'all' and opt['city'] != 'all' and opt['blood_group'] == 'all':
                    sql = 'select * from PERSONALDETAILS where CITY=?'
                    response['filters'] = filter_by_one_param(sql, opt['city'])
                    response['filter_by'] = 'State'
                    response['filter1_city'] = city_filter(None)
                    return jsonify(response)

                elif opt['state'] == 'all' and opt['city'] != 'all' and opt['blood_group'] != 'all':
                    sql = 'select * from PERSONALDETAILS where CITY=? and BLOODGROUP=' + b_group
                    response['filters'] = filter_by_one_param(sql, opt['city'])
                    return jsonify(response)

                elif opt['state'] == 'all' and opt['city'] == 'all' and opt['blood_group'] != 'all':
                    print(b_group)
                    sql = 'select * from PERSONALDETAILS where BLOODGROUP=' + b_group
                    response['filters'] = display_donors(sql)
                    return jsonify(response)

                elif opt['state'] == 'all' and opt['city'] == 'all' and opt['blood_group'] == 'all':
                    response['filters'] = display_donors('select * from PERSONALDETAILS')
                    response['filter_by'] = 'State'
                    response['filter1_city'] = city_filter(None)
                    return response

                sql = 'select * from PERSONALDETAILS where STATE=? and CITY=? and BLOODGROUP=' + b_group
                response['filters'] = filter_by_two_params(sql, opt['state'], opt['city'])
                return response

            elif 'emails' in opt:
                for user in opt['emails']:
                    msg = Message('Request For Plasma', sender='noreplyplasmadonor@gmail.com', recipients=[user])
                    msg.body = 'Would you like to make a plasma donation?'
                    try:
                        mail.send(msg)
                        response['mail_sent'] = 'Sent'
                    except Exception:
                        response['mail_sent'] = 'Not Sent'
                        break
            return jsonify(response)

        else:
            b_groups = ['A+ve', 'A-ve', 'B+ve', 'B-ve', 'O+ve', 'O-ve', 'AB+ve', 'AB-ve']

            sql = 'select distinct STATE, CITY from PERSONALDETAILS'
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.execute(stmt)
            states, cities = [], []

            dictionary = ibm_db.fetch_assoc(stmt)
            while dictionary:
                for x in dictionary:
                    dictionary[x] = dictionary[x].strip()
                cities.append(dictionary['CITY'.strip()])
                states.append(dictionary['STATE'].strip())
                dictionary = ibm_db.fetch_assoc(stmt)
            states = list(set(states))
            cities = list(set(cities))
            states.sort()
            cities.sort()
            return render_template('request_page.html', res=display_donors('select * from PERSONALDETAILS'), b_groups=b_groups, states=states, cities=cities)
    else:
        return redirect(url_for('sprint3.login_as', redirect_to='Org'))


@sprint3.route('/org-profile', methods=['GET', 'POST'])
def admin():
    if 'Organisation' in session:
        if request.method == 'POST':
            response = dict()
            data = request.json
            if 'Email' in data:
                sql2 = 'select NAME from ORGANISATION_DETAILS where EMAIL=?'
                stmt2 = ibm_db.prepare(conn, sql2)
                ibm_db.bind_param(stmt2, 1, session['Organisation'])
                ibm_db.execute(stmt2)
                fetch = ibm_db.fetch_assoc(stmt2)
                if data['BtnType'] == 'AccpBtn' or data['BtnType'] == 'declineBtn':
                    msg = Message('Plasma Donation Request Status', sender='noreplyplasmadono', recipients=[data['Email']])
                    if data['BtnType'] == 'AccpBtn':
                        msg.body = f'''Hello! This is {fetch['NAME']}. Your request for plasma donation have been approved.
A mail will be sent shortly for appointment. Thank you'''
                        mail.send(msg)

                        sql = 'update DONATE_REQUESTS set REQUEST_STATUS=\'ACCEPTED\' where DONOR_EMAIL=? and ORG_EMAIL=?'
                        stmt = ibm_db.prepare(conn, sql)
                        ibm_db.bind_param(stmt, 1, data['Email'])
                        ibm_db.bind_param(stmt, 2, session['Organisation'])
                        ibm_db.execute(stmt)
                        response['sent-status'] = 'success'
                    else:
                        msg.body = f'''Hello! This is {fetch['NAME']}. Thank you for your interest of plasma donation.
Sorry to decline this request. Thank you'''
                        mail.send(msg)

                        sql = 'update DONATE_REQUESTS set REQUEST_STATUS=\'DECLINED\' where DONOR_EMAIL=? and ORG_EMAIL=?'
                        stmt = ibm_db.prepare(conn, sql)
                        ibm_db.bind_param(stmt, 1, data['Email'])
                        ibm_db.bind_param(stmt, 2, session['Organisation'])
                        ibm_db.execute(stmt)
                        response['sent-status'] = 'success'
                elif data['BtnType'] == 'ReqBtn':
                    msg = Message('Plasma Donation Request Status', sender='noreplyplasmadono', recipients=[data['Email']])
                    msg.body = f'''Hello! This is {fetch['NAME']}. We're in need of plasma.
If you're interested to donate. Please send your reply to this mail.'''
                    mail.send(msg)
                    response['sent-status'] = 'success'
                return response
            else:
                sql1 = 'select * from ORG_DONOR_REGISTER_TABLE where EMAIL=?'
                stmt1 = ibm_db.prepare(conn, sql1)
                ibm_db.bind_param(stmt1, 1, data['email'])
                ibm_db.execute(stmt1)
                fetch = ibm_db.fetch_assoc(stmt1)
                if fetch:
                    response['status'] = 'Exist'
                    return response

                sql = 'insert into ORG_DONOR_REGISTER_TABLE values (?, ?, ?, ?, ?, ?)'
                stmt = ibm_db.prepare(conn, sql)
                ibm_db.bind_param(stmt, 1, data['fname'])
                ibm_db.bind_param(stmt, 2, data['lname'])
                ibm_db.bind_param(stmt, 3, data['b_group'])
                ibm_db.bind_param(stmt, 4, data['email'])
                ibm_db.bind_param(stmt, 5, data['contact'])
                ibm_db.bind_param(stmt, 6, session['Organisation'])
                ibm_db.execute(stmt)
                response['status'] = 'Done'
                return response
        else:
            sql = 'select NAME from ORGANISATION_DETAILS where EMAIL=?'
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, session['Organisation'])
            ibm_db.execute(stmt)
            fetch = ibm_db.fetch_assoc(stmt)

            details = fetch['NAME']

            sql = 'select * from DONATE_REQUESTS where ORG_EMAIL=? and REQUEST_STATUS=\'PENDING\''
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, session['Organisation'])
            ibm_db.execute(stmt)
            fetch = ibm_db.fetch_assoc(stmt)

            res = []
            while fetch:
                res.append(fetch)
                fetch = ibm_db.fetch_assoc(stmt)

            sql = 'select * from ORG_DONOR_REGISTER_TABLE where "ORG_EMAIL"=?'
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, session['Organisation'])
            ibm_db.execute(stmt)
            fetch = ibm_db.fetch_assoc(stmt)
            res2 = []
            while fetch:
                res2.append(fetch)
                fetch = ibm_db.fetch_assoc(stmt)

Project-Development-Phase/sprint3/templates/login.html
{% extends 'index.html' %}
{% block title %}Login Required{% endblock title %}

{% block content %}
    <div class="fullscreen">
        <nav class="navbar bg-white">
            <div class="ps-3">
                <a class="navbar-icon">Plasma Donor</a>
                <div class="nav-content">
                    <a class="nav-content-item" href="{{ url_for('sprint1.home') }}">HOME</a>
                </div>
            </div>
        </nav>
        <div class="container-fluid" style="position: absolute; height: 91vh; width: 100%; display: flex; justify-content: center; align-items: center">
            <div class="container" style="width: 450px; border: 1px solid lightgrey; padding: 40px 40px 30px; border-radius: 0.5rem">
                <form method="POST" autocomplete="off" id="loginform">
                    <h2 style="font-family: Roboto, sans-serif">Login</h2>
                    <hr>
                    <div class="alert alert-info" type="alert" id="RequestLoginForDonorPage" style="display: none">
                        Please login to proceed to Request page.
                    </div>
                    <input class="ignore" type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <div class="pb-2">
                        <label for="UserName" class="form-label">Username <span id="UserNameValidate"></span></label>
                        <input class="form-control" type="email" id="UserName" name="username" placeholder="username@gmail.com">
                    </div>
                    <div class="pb-2">
                        <label for="LoginPassword" class="form-label">Password <span id="LoginPasswordValidate"></span></label>
                        <div class="input-group">
                            <input class="form-control" type="password" id="LoginPassword"  name="loginpassword" placeholder="Password">
                            <span class="input-group-text eye fa-solid fa-eye" id="ShowLoginPassword"></span>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end mb-2">
                        <a href="/request-reset">Forgot Password?</a>
                    </div>
                    <hr class="mt-0">
                    <div class="d-grid gap-2 pb-2">
                        <button class="btn btn-primary" type="submit" id="login-button">LOGIN</button>
                        <button class="btn btn-primary" id="spinner-button" disabled>
                            <span class="spinner-border text-light"></span>
                        </button>
                    </div>
                    <span class="d-flex justify-content-center" style="white-space: pre">Don't have an account? <a href="/register-as-org">Create Account</a></span>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{{ url_for('sprint1.static', filename="js/login.js") }}"></script>
    <script>
        const csrf_token = "{{ csrf_token() }}";
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });
    </script>
    <script>
        $(window).on('load', function (){
            $('#RequestLoginForDonorPage').css({display: 'block'});
            const path_name = window.location.pathname;
            if (path_name === '/login-as/Org') {
                $('#login-button').attr('data-userinfo', 'AsOrg');
            }
            else {
                $('#login-button').attr('data-userinfo', 'AsDonor');
            }
        });
    </script>
{% endblock javascript %}

Project-Development-Phase/sprint3/templates/org_profile.html
{% extends 'index.html' %}
{% block title %}Admin{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('sprint3.static', filename="css/org.css") }}">
{% endblock style %}

{% block content %}
    <div class="fullscreen">
        <nav class="navbar bg-white">
            <div class="ps-3">
                <a class="navbar-icon" href="{{ url_for('sprint1.home') }}">Plasma Donor</a>
                <div class="nav-content">
                    <a class="nav-content-item" href="{{ url_for('sprint1.home') }}">HOME</a>
                    <a class="nav-content-item" style="pointer-events: none" href="{{ url_for('sprint3.donor_request') }}">REQUEST</a>
                </div>
            </div>
            <div class="nav-content-right">
                <a class="nav-content-item" href="/org-logout">LOGOUT</a>

                <div class="dropstart dropdown-align">
                    <a class="fa-solid fa-bars" data-bs-toggle="dropdown" id="NavItems"></a>
                    <div class="dropdown-menu" aria-labelledby="NavItems">
                        <a class="dropdown-item" href="{{ url_for('sprint1.home') }}">HOME</a>
                        <a class="dropdown-item" href="#">REQUEST</a>
                        <hr class="mb-2 mt-2">
                        <a class="dropdown-item" href="/org-logout">LOGOUT</a>
                    </div>
                </div>
            </div>
        </nav>

        <div class="container-fluid" style="height: 91vh; box-shadow: 0 3px 8px rgba(0, 0, 0, 30%)">
            <div class="container pe-0 ps-0" style="height: 91vh; float: left; border-right: 1px solid lightgrey; width: 20%; overflow: scroll">
                <div class="d-grid gap-1 mt-3">
                    <strong class="ps-2" style="font-size: 1.5rem; padding: 0 10px;">{{ details }}</strong>
                    <hr class="mt-2">
                    <p class="ps-2 mb-1 LeftPane active" id="LP1">Dashboard</p>
                    <p class="ps-2 mt-0 mb-1 LeftPane" id="LP2">Donors</p>
                    <p class="ps-2 mt-0 LeftPane" id="LP3">Register Donor</p>
                </div>
            </div>
            <div class="container Tab active" style="width: 80%; height: 91vh; float: left; overflow: scroll; padding: 25px 30px" id="Tab1">
                <div class="p-2 float-start">
                    <div class="row row-cols-2">
                        <div class="col pe-0" style="margin: auto">
                            <label for="OrgTableFilter">Blood Group:</label>
                        </div>
                        <div class="col ps-1">
                            <select class="form-select" id="OrgTableFilter">
                                <option selected value="all">All</option>
                                <option value="A+ve">A+ve</option>
                                <option value="A-ve">A-ve</option>
                                <option value="B+ve">B+ve</option>
                                <option value="B-ve">B-ve</option>
                                <option value="O+ve">O+ve</option>
                                <option value="O-ve">O-ve</option>
                                <option value="AB+ve">AB+ve</option>
                                <option value="AB-ve">AB-ve</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="p-2 float-end" style="width: 400px">
                    <input type="search" class="form-control" id="OrgReqSearch" aria-label="OrgReqSearch" placeholder="Search">
                </div>
                <div class="container p-0" style="width: 99% ;height: fit-content;; max-height: 76vh; border: 1px solid lightgrey; overflow: scroll">
                    <table class="table Table1 active mb-0" style="text-align: center">
                        <thead class="table-secondary">
                            <tr>
                                <th scope="col">S.No</th>
                                <th scope="col">Donor Name</th>
                                <th scope="col">Donor Blood-Group</th>
                                <th scope="col" colspan="2">Action</th>
                            </tr>
                        </thead>
                        <tbody id="Table1">
                            {% for row in res %}
                                <tr>
                                    <td>{{ res.index(row) + 1 }}</td>
                                    <td>{{ row['DONOR_NAME'] }}</td>
                                    <td>{{ row['DONOR_BLOODGROUP'] }}</td>
                                    <td>
                                        <button class="btn actionBtn btn-sm btn-primary me-1" data-donor-name="{{ row['DONOR_NAME'] }}" data-donor-email="{{ row['DONOR_EMAIL'] }}" id="AccpBtn">Accept</button>
                                        <button class="btn actionBtn btn-sm btn-light" style="box-shadow: 0 0 3px rgba(0,0,0,40%)" data-donor-name="{{ row['DONOR_NAME'] }}" data-donor-email="{{ row['DONOR_EMAIL'] }}" id="declineBtn">Decline</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <table class="table Table2 mb-0" style="text-align: center">
                        <thead class="table-secondary">
                            <tr>
                                <th scope="col">S.No</th>
                                <th scope="col">Donor Name</th>
                                <th scope="col">Blood-Group</th>
                                <th scope="col">PHONE NUMBER</th>
                                <th scope="col">EMAIL</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody id="Table2">
                            {% for donor in donors %}
                                <tr>
                                    <td>{{ donors.index(donor) + 1 }}</td>
                                    <td>{{ donor['FNAME'] + ' ' + donor['LNAME'] }}</td>
                                    <td>{{ donor['BLOODGROUP'] }}</td>
                                    <td>{{ donor['PHONENUMBER'] }}</td>
                                    <td>{{ donor['EMAIL'] }}</td>
                                    <td>
                                        <button class="btn actionBtn btn-sm btn-primary" data-donor-email="{{ donor['EMAIL'] }}" id="ReqBtn">Request</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="container Tab" style="width: 80%; height: 91vh; float: left; overflow: scroll; padding: 25px 30px" id="Tab2">
                <div class="container w-50" style="min-height: 76vh; border: 1px solid lightgrey; padding: 70px 40px 20px">
                    <form method="POST" id="OrgDonorRegisterForm" autocomplete="off">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <label class="form-label mb-1" for="FirstName">Donor's First Name</label>
                        <input type="text" class="form-control mb-2" name="fname" id="FirstName" required>
                        <label class="form-label mb-1" for="LastName">Donor's Last Name</label>
                        <input type="text" class="form-control mb-2" name="lname" id="LastName" required>
                        <label for="BloodGroup" class="form-label mb-1">Donor's Blood Group</label>
                        <select class="form-select mb-2" id="BloodGroup" name="b_group" required>
                            <option selected value="all">All</option>
                            <option value="A+ve">A+ve</option>
                            <option value="A-ve">A-ve</option>
                            <option value="B+ve">B+ve</option>
                            <option value="B-ve">B-ve</option>
                            <option value="O+ve">O+ve</option>
                            <option value="O-ve">O-ve</option>
                            <option value="AB+ve">AB+ve</option>
                            <option value="AB-ve">AB-ve</option>
                        </select>
                        <label class="form-label mb-1" for="Email">Donor's Email</label>
                        <input type="email" class="form-control mb-2" name="email" id="Email" required>
                        <label class="form-label mb-1" for="ContactNo">Donor's Phone Number</label>
                        <input type="tel" class="form-control mb-2" name="contact" id="ContactNo" required>
                        <hr>
                        <div class="d-grid">
                            <button class="btn btn-primary" type="submit">SUBMIT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script>
        const csrf_token = "{{ csrf_token() }}";
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });
    </script>
    <script src="{{ url_for('sprint3.static', filename="js/org_profile.js") }}"></script>
{% endblock javascript %}